#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

typedef unsigned int u32;
struct FontConfig { u32 vrom,blob,image,reloc,text,entry,crc,abi; };
volatile struct FontConfig af_font_test_config;
extern void *af_extended_font_image;
extern int af_extended_font_init(void);
static unsigned char memory[0x5000] __attribute__((aligned(16)));
static unsigned char blob[0x4000];
static u32 events[32],used,requested,fail_alloc,fail_dma,corrupt,fail_execute,heap,alignment,nested;
static void event(u32 code) {
    events[used++]=code;
    if (nested==code) { assert(af_extended_font_init()==0); }
}
void *af_font_test_allocate(u32 bytes) { event(1);requested=bytes;return fail_alloc?NULL:memory+alignment; }
void af_font_test_release(void *p) { assert(p==memory+alignment);event(7); }
u32 af_font_test_address(void *p) { assert(p==memory+alignment);return heap; }
int af_font_test_dma(void *p,u32 vrom,u32 bytes) {
    event(2);assert(!((size_t)p&15));assert(vrom==0x03400000);assert(bytes==af_font_test_config.blob);
    memcpy(p,blob,bytes);if (corrupt) ((unsigned char *)p)[corrupt-1]^=1;
    return fail_dma;
}
void af_font_test_relocate(void *p,void *r,u32 origin) {
    event(3);assert((unsigned char *)r==(unsigned char *)p+af_font_test_config.image);
    assert(origin==0x80C00000);assert(!memcmp(p,blob,af_font_test_config.blob));
}
void af_font_test_writeback(void *p,u32 bytes) { (void)p;event(4);assert(bytes==af_font_test_config.image); }
void af_font_test_invalidate(void *p,u32 bytes) { (void)p;event(5);assert(bytes==af_font_test_config.text); }
int af_font_test_execute(void *p) { event(6);assert(!memcmp(p,blob,af_font_test_config.blob));return fail_execute?0:1; }
static void reset(void) {
    af_extended_font_image=NULL;used=0;requested=0;fail_alloc=0;fail_dma=0;corrupt=0;fail_execute=0;
    heap=0x80200000;alignment=0;nested=0;memset(memory,0xCC,sizeof(memory));
    /* CRC-32 of bytes 0..95, independently generated by Python zlib. */
    af_font_test_config=(struct FontConfig){0x03400000,96,64,32,32,0,0x51C87372,0x41464701};
    for (u32 i=0;i<96;++i) blob[i]=(unsigned char)i;
}
static void expect(int result,const u32 *order,u32 count) {
    assert(af_extended_font_init()==result);assert(used==count);
    assert(!memcmp(events,order,count*sizeof(u32)));
    if (result && count) {
        assert(af_extended_font_image!=NULL);assert(requested==111);
        assert(af_extended_font_init()==1 && used==count);
    } else assert(af_extended_font_image==NULL);
}
int main(void) {
    const u32 success[]={1,2,3,4,5,6},release[]={1,2,7},execute_fail[]={1,2,3,4,5,6,7};
    reset();af_font_test_config=(struct FontConfig){0};expect(1,success,0);
    for (u32 a=0;a<16;++a) { reset();alignment=a;expect(1,success,6); }
    for (u32 n=1;n<=6;++n) { reset();nested=n;expect(1,success,6); }
    reset();fail_alloc=1;expect(0,success,1);
    reset();fail_dma=1;expect(0,release,3);
    reset();fail_execute=1;expect(0,execute_fail,7);
    for (u32 i=1;i<=96;++i) { reset();corrupt=i;expect(0,release,3); }
    const u32 bad_heap[]={0,0x8019C8DF,0x80400000-110,0x80400000,0xFFFFFFFF};
    const u32 heap_fail[]={1,7};
    for (u32 i=0;i<sizeof(bad_heap)/sizeof(*bad_heap);++i) { reset();heap=bad_heap[i];expect(0,heap_fail,2); }
    for (u32 field=0;field<8;++field) {
        const u32 values[]={0,1,15,0xFFFFFFFF};
        for (u32 i=0;i<4;++i) {
            reset();u32 old=((volatile u32 *)&af_font_test_config)[field];
            if (values[i]==old) continue;
            ((volatile u32 *)&af_font_test_config)[field]=values[i];
            if (field==6) expect(0,release,3);else expect(0,success,0);
        }
    }
    reset();fail_dma=1;expect(0,release,3);used=0;fail_dma=0;expect(1,success,6);
    puts("persistent font loader ownership and failures passed");
    return 0;
}
